---
title: Gezelschapsspel
hero_image: images/banner.png
description: Gebruik je micro:bit om een gezelschapsspel te maken!
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: Inleiding
  - title: Jouw idee
  - title: Bouw en test
    completion:
      - engaged
      - internal
  - title: Controlelijst
    completion:
      - external
  - title: Deel en speel
  - title: Wat kun je verder nog doen?
